//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wx_site.RenshiService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RenshiService.renshiSoap")]
    public interface renshiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEmpinfo(string emp_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpinfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpinfoAsync(string emp_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHRT010TB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHRT010TB(string emp_no, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHRT010TB", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetHRT010TBAsync(string emp_no, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGongZi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetGongZi(string emp_no, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGongZi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetGongZiAsync(string emp_no, string month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddHEX001TB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AddHEX001TB(wx_site.RenshiService.HEX001TB hex001tb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddHEX001TB", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AddHEX001TBAsync(wx_site.RenshiService.HEX001TB hex001tb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckHEX001TB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CheckHEX001TB(wx_site.RenshiService.HEX001TB hex001tb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckHEX001TB", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CheckHEX001TBAsync(wx_site.RenshiService.HEX001TB hex001tb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchHEX001TB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchHEX001TB(wx_site.RenshiService.HEX001TB hex001tb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchHEX001TB", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchHEX001TBAsync(wx_site.RenshiService.HEX001TB hex001tb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UserCheck(string emp_no, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UserCheckAsync(string emp_no, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Change_pwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Change_pwd(string emp_no, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Change_pwd", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Change_pwdAsync(string emp_no, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNewid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetNewidAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HEX001TB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string emp_noField;
        
        private System.DateTime ex_dateField;
        
        private string dilig_cdField;
        
        private string ex_btimeField;
        
        private string ex_etimeField;
        
        private string ex_remarkField;
        
        private string ck_flgField;
        
        private string ck_noField;
        
        private string ck_remarkField;
        
        private string ck_ipField;
        
        private string ins_noField;
        
        private string ins_ipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string emp_no {
            get {
                return this.emp_noField;
            }
            set {
                this.emp_noField = value;
                this.RaisePropertyChanged("emp_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ex_date {
            get {
                return this.ex_dateField;
            }
            set {
                this.ex_dateField = value;
                this.RaisePropertyChanged("ex_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dilig_cd {
            get {
                return this.dilig_cdField;
            }
            set {
                this.dilig_cdField = value;
                this.RaisePropertyChanged("dilig_cd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ex_btime {
            get {
                return this.ex_btimeField;
            }
            set {
                this.ex_btimeField = value;
                this.RaisePropertyChanged("ex_btime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ex_etime {
            get {
                return this.ex_etimeField;
            }
            set {
                this.ex_etimeField = value;
                this.RaisePropertyChanged("ex_etime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ex_remark {
            get {
                return this.ex_remarkField;
            }
            set {
                this.ex_remarkField = value;
                this.RaisePropertyChanged("ex_remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ck_flg {
            get {
                return this.ck_flgField;
            }
            set {
                this.ck_flgField = value;
                this.RaisePropertyChanged("ck_flg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ck_no {
            get {
                return this.ck_noField;
            }
            set {
                this.ck_noField = value;
                this.RaisePropertyChanged("ck_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ck_remark {
            get {
                return this.ck_remarkField;
            }
            set {
                this.ck_remarkField = value;
                this.RaisePropertyChanged("ck_remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ck_ip {
            get {
                return this.ck_ipField;
            }
            set {
                this.ck_ipField = value;
                this.RaisePropertyChanged("ck_ip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ins_no {
            get {
                return this.ins_noField;
            }
            set {
                this.ins_noField = value;
                this.RaisePropertyChanged("ins_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ins_ip {
            get {
                return this.ins_ipField;
            }
            set {
                this.ins_ipField = value;
                this.RaisePropertyChanged("ins_ip");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface renshiSoapChannel : wx_site.RenshiService.renshiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class renshiSoapClient : System.ServiceModel.ClientBase<wx_site.RenshiService.renshiSoap>, wx_site.RenshiService.renshiSoap {
        
        public renshiSoapClient() {
        }
        
        public renshiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public renshiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public renshiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public renshiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetEmpinfo(string emp_no) {
            return base.Channel.GetEmpinfo(emp_no);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpinfoAsync(string emp_no) {
            return base.Channel.GetEmpinfoAsync(emp_no);
        }
        
        public System.Data.DataSet GetHRT010TB(string emp_no, string month) {
            return base.Channel.GetHRT010TB(emp_no, month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetHRT010TBAsync(string emp_no, string month) {
            return base.Channel.GetHRT010TBAsync(emp_no, month);
        }
        
        public System.Data.DataSet GetGongZi(string emp_no, string month) {
            return base.Channel.GetGongZi(emp_no, month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetGongZiAsync(string emp_no, string month) {
            return base.Channel.GetGongZiAsync(emp_no, month);
        }
        
        public System.Data.DataSet AddHEX001TB(wx_site.RenshiService.HEX001TB hex001tb) {
            return base.Channel.AddHEX001TB(hex001tb);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AddHEX001TBAsync(wx_site.RenshiService.HEX001TB hex001tb) {
            return base.Channel.AddHEX001TBAsync(hex001tb);
        }
        
        public System.Data.DataSet CheckHEX001TB(wx_site.RenshiService.HEX001TB hex001tb) {
            return base.Channel.CheckHEX001TB(hex001tb);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CheckHEX001TBAsync(wx_site.RenshiService.HEX001TB hex001tb) {
            return base.Channel.CheckHEX001TBAsync(hex001tb);
        }
        
        public System.Data.DataSet SearchHEX001TB(wx_site.RenshiService.HEX001TB hex001tb) {
            return base.Channel.SearchHEX001TB(hex001tb);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchHEX001TBAsync(wx_site.RenshiService.HEX001TB hex001tb) {
            return base.Channel.SearchHEX001TBAsync(hex001tb);
        }
        
        public bool UserCheck(string emp_no, string pwd) {
            return base.Channel.UserCheck(emp_no, pwd);
        }
        
        public System.Threading.Tasks.Task<bool> UserCheckAsync(string emp_no, string pwd) {
            return base.Channel.UserCheckAsync(emp_no, pwd);
        }
        
        public bool Change_pwd(string emp_no, string pwd) {
            return base.Channel.Change_pwd(emp_no, pwd);
        }
        
        public System.Threading.Tasks.Task<bool> Change_pwdAsync(string emp_no, string pwd) {
            return base.Channel.Change_pwdAsync(emp_no, pwd);
        }
        
        public System.Data.DataSet GetNewid() {
            return base.Channel.GetNewid();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetNewidAsync() {
            return base.Channel.GetNewidAsync();
        }
    }
}
